### ISSUE TITLE
Missing imports in wilds_utils.py 

### ISSUE THREAD

**Issue by sebtsh** [runame/laplace-redux#2]
Hi,

When importing `utils/wilds_utils.py`, it tries the following imports: 

```
from configs.utils import populate_defaults
from examples.models.initializer import initialize_model
from examples.transforms import initialize_transform
```

But these fail. It seems that the `configs` module has no `utils` file, and there is no `examples` module. I have installed the WILDS module version 1.1.0.

**Comment by runame** [comment]
Hi,

Did you also follow the instructions [here](https://github.com/p-lambda/wilds/tree/v1.1.0#default-models)?

**Comment by sebtsh** [comment]
Thanks, that solved the issue. The relevant code requires installing WILDS from source instead of from the pip package.
