### ISSUE TITLE
Sum-squared-error in Regression Calibration Error Calculation

### ISSUE THREAD

**Issue by yutongy98** [runame/laplace-redux#3]
Hi, thanks for the comprehensive experiments! In the calculation of the regression calibration error (https://github.com/runame/laplace-redux/blob/main/utils/utils.py#L245), the last line is `cal = T*mean_squared_error(ps, p_hats)  # Sum-squared-error`. I wonder, if the mse term should be scaled with `len(ps)` (the number of bins) instead of `T` (the number of samples in the dataset)? Also according to the equation 9 in  Kuleshov et al. ICML 2018, the `cal` error is only the summed square error among the `m` confidence levels. Could you please kindly clarify this point? Thank you in advance!

**Comment by runame** [comment]
Hi, sorry for the late reply. I'm not sure if there was a reason for this discrepancy to the equation in the paper, but I would just implement what you think makes the most sense for your use case (unless maybe you want to compare to our numbers). @wiseodd also suggested that you could take a look at [torchmetrics](https://github.com/Lightning-AI/torchmetrics) and [net:cal](https://github.com/EFS-OpenSource/calibration-framework) to see if they implement anything you might want to use.

**Comment by yutongy98** [comment]
Great, thank you point is out! I will close this issue:)
